[project]
name = "car-price-perdiction"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy",
    "pandas",
    "scikit-learn",
    "xgboost",
    "fastapi[standard]"
]
